### ISSUE TITLE
Fail to evaluate 

### ISSUE THREAD

**Issue by Ching-Nam** [hsiangyuzhao/PANet#1]
Hello, dear author. When I tried to run the code, I received an error. It said that the dice metric only had one return value, but we expected two, for example we want dice_et and dice_et_not_nan. Is there any way I can fix this problem? Thank you so much.

**Comment by hsiangyuzhao** [comment]
It seems that the issue comes from the version of monai. In the early versions of monai, when calculating metrics, two return values are returned where the second indicates whether there are nans, but in the latest version only one value is returned by default. If we want the older behavior, please turn "get_not_nans" flag to `True`.
