### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by ZNzhr** [hsiangyuzhao/PANet#3]
Hello, dear author. I have encountered some troubles when trying to implement the 2D multi-lesion segmentation. I want to get the code for 2D multi-lesion segmentation.If possible, can you send me the source code?

**Comment by hsiangyuzhao** [comment]
Theoretically the 2D segmentation code could be implemented according to the released 3D code without much effort. We didn't release them because the code has been written long time ago and is not written gracefully :rofl:. You could provide more details about your current issue (e.g. where you are stuck, loading data? building model? evaluation? etc. ), and I may help you fix it.

**Comment by ZNzhr** [comment]
Thank you for your reply.Now I am trying to modify the code into a 2D segmentation code.If there is any problem in the future,I will consult you again.

**Comment by hsiangyuzhao** [comment]
Thanks for the interest to our research. Please feel free to reopen the issue if you encounter any problems when modifying the code to 2D. I am glad to help :smiley:

**Comment by Saillxl** [comment]
@ZNzhr Have you achieve it?
